// <auto-generated />
using System;
using BasicEcommerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BasicEcommerce.Migrations
{
    [DbContext(typeof(EcommerceContext))]
    [Migration("20250603164709_Inicio")]
    partial class Inicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BasicEcommerce.Models.Products", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("42e0396d-66d3-4e3b-a904-5144788b92f3"),
                            Description = "Sonido de alta fidelidad con cancelación de ruido activa y 24 horas de batería.",
                            MainImageUrl = "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Auriculares Inalámbricos Pro",
                            Price = 129.99m,
                            Stock = 75
                        },
                        new
                        {
                            ProductId = new Guid("dda144ee-2eec-4357-9359-678285549ac1"),
                            Description = "Diseño compacto con switches Cherry MX Red y retroiluminación RGB personalizable.",
                            MainImageUrl = "https://images.unsplash.com/photo-1633315754878-b5a3b0ce64f7?q=80&w=2076&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Teclado Mecánico RGB",
                            Price = 89.50m,
                            Stock = 120
                        },
                        new
                        {
                            ProductId = new Guid("573c74a3-2919-459d-8ac1-caed7862bd98"),
                            Description = "Diseño ergonómico, sensor de 16000 DPI y 6 botones programables. Solo 60g.",
                            MainImageUrl = "https://images.unsplash.com/photo-1605773527852-c546a8584ea3?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Ratón Gaming Ultraligero",
                            Price = 49.99m,
                            Stock = 90
                        },
                        new
                        {
                            ProductId = new Guid("867308cc-968f-40da-89d9-d7dcdb73071d"),
                            Description = "Panel VA con resolución QHD (2560x1440), 144Hz de refresco y 1ms de respuesta.",
                            MainImageUrl = "https://images.unsplash.com/photo-1666771410003-8437c4781d49?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Monitor Curvo 27'' QHD",
                            Price = 299.00m,
                            Stock = 40
                        },
                        new
                        {
                            ProductId = new Guid("72dfd31b-a004-4714-baa9-8ad42c43e43c"),
                            Description = "Ideal para videollamadas y streaming, con enfoque automático y micrófono integrado.",
                            MainImageUrl = "https://images.unsplash.com/photo-1636569826709-8e07f6104992?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Webcam Full HD 1080p",
                            Price = 35.75m,
                            Stock = 200
                        },
                        new
                        {
                            ProductId = new Guid("9b332067-56d1-4319-a488-dc33d073e1aa"),
                            Description = "Almacenamiento portátil de alta velocidad con conexión USB 3.0. Delgado y resistente.",
                            MainImageUrl = "https://images.unsplash.com/photo-1613070541337-b40942ee6527?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Disco Duro Externo 2TB",
                            Price = 75.25m,
                            Stock = 60
                        },
                        new
                        {
                            ProductId = new Guid("f0e0d750-1ec7-40a3-a604-b321c6b99a01"),
                            Description = "Monitor de ritmo cardíaco, GPS integrado y resistencia al agua. Compatible con iOS/Android.",
                            MainImageUrl = "https://images.unsplash.com/photo-1733570890170-49be2550189b?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Smartwatch Deportivo X1",
                            Price = 99.00m,
                            Stock = 85
                        },
                        new
                        {
                            ProductId = new Guid("9502ca89-fca4-4898-b94c-c3c9d67f47a3"),
                            Description = "Sonido potente en 360º, 12 horas de batería y resistencia IPX7 al agua.",
                            MainImageUrl = "https://images.unsplash.com/photo-1589256469067-ea99122bbdc4?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Altavoz Bluetooth Portátil",
                            Price = 59.99m,
                            Stock = 150
                        },
                        new
                        {
                            ProductId = new Guid("b116d3b9-007f-4da0-a39e-4eb16aadfa34"),
                            Description = "Carga tu portátil, tablet y smartphone a máxima velocidad. Diseño compacto.",
                            MainImageUrl = "https://images.unsplash.com/photo-1731616103600-3fe7ccdc5a59?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Cargador Rápido USB-C 65W",
                            Price = 25.00m,
                            Stock = 300
                        },
                        new
                        {
                            ProductId = new Guid("8caf20fb-9e5d-4e74-9e05-df47af133664"),
                            Description = "Diseño ergonómico, compartimentos ocultos y puerto de carga USB integrado.",
                            MainImageUrl = "https://images.unsplash.com/photo-1668114844900-537ab91478b9?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Mochila Antirrobo para Portátil",
                            Price = 45.80m,
                            Stock = 110
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
