// <auto-generated />
using System;
using BasicEcommerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BasicEcommerce.Migrations
{
    [DbContext(typeof(EcommerceContext))]
    [Migration("20250606181101_orderModificado")]
    partial class orderModificado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BasicEcommerce.Models.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RedsysOrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BasicEcommerce.Models.OrderItem", b =>
                {
                    b.Property<Guid>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("BasicEcommerce.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("fd330f46-3c07-469a-b092-92a26a159f07"),
                            Description = "Sonido de alta fidelidad con cancelación de ruido activa y 24 horas de batería.",
                            MainImageUrl = "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Auriculares Inalámbricos Pro",
                            Price = 129.99m,
                            Stock = 75
                        },
                        new
                        {
                            ProductId = new Guid("38a96d17-f9fb-48c2-ae40-0dd51cc0fef9"),
                            Description = "Diseño compacto con switches Cherry MX Red y retroiluminación RGB personalizable.",
                            MainImageUrl = "https://images.unsplash.com/photo-1633315754878-b5a3b0ce64f7?q=80&w=2076&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Teclado Mecánico RGB",
                            Price = 89.50m,
                            Stock = 120
                        },
                        new
                        {
                            ProductId = new Guid("7a792215-9953-4036-b316-9f61d91ff44c"),
                            Description = "Diseño ergonómico, sensor de 16000 DPI y 6 botones programables. Solo 60g.",
                            MainImageUrl = "https://images.unsplash.com/photo-1605773527852-c546a8584ea3?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Ratón Gaming Ultraligero",
                            Price = 49.99m,
                            Stock = 90
                        },
                        new
                        {
                            ProductId = new Guid("8030810e-6229-440b-871d-4f037af5c5d2"),
                            Description = "Panel VA con resolución QHD (2560x1440), 144Hz de refresco y 1ms de respuesta.",
                            MainImageUrl = "https://images.unsplash.com/photo-1666771410003-8437c4781d49?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Monitor Curvo 27'' QHD",
                            Price = 299.00m,
                            Stock = 40
                        },
                        new
                        {
                            ProductId = new Guid("9090e95d-ef34-428e-8d7d-4e95d85f0c22"),
                            Description = "Ideal para videollamadas y streaming, con enfoque automático y micrófono integrado.",
                            MainImageUrl = "https://images.unsplash.com/photo-1636569826709-8e07f6104992?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Webcam Full HD 1080p",
                            Price = 35.75m,
                            Stock = 200
                        },
                        new
                        {
                            ProductId = new Guid("5896d47a-0bea-4672-9ebe-b27a090dce18"),
                            Description = "Almacenamiento portátil de alta velocidad con conexión USB 3.0. Delgado y resistente.",
                            MainImageUrl = "https://images.unsplash.com/photo-1613070541337-b40942ee6527?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Disco Duro Externo 2TB",
                            Price = 75.25m,
                            Stock = 60
                        },
                        new
                        {
                            ProductId = new Guid("9645707a-9308-4c50-b290-0aca88474da1"),
                            Description = "Monitor de ritmo cardíaco, GPS integrado y resistencia al agua. Compatible con iOS/Android.",
                            MainImageUrl = "https://images.unsplash.com/photo-1733570890170-49be2550189b?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Smartwatch Deportivo X1",
                            Price = 99.00m,
                            Stock = 85
                        },
                        new
                        {
                            ProductId = new Guid("b4890249-4572-4109-a0cc-911b8770fa41"),
                            Description = "Sonido potente en 360º, 12 horas de batería y resistencia IPX7 al agua.",
                            MainImageUrl = "https://images.unsplash.com/photo-1589256469067-ea99122bbdc4?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Altavoz Bluetooth Portátil",
                            Price = 59.99m,
                            Stock = 150
                        },
                        new
                        {
                            ProductId = new Guid("53452542-5e1c-4dde-b01f-cab1a08a4473"),
                            Description = "Carga tu portátil, tablet y smartphone a máxima velocidad. Diseño compacto.",
                            MainImageUrl = "https://images.unsplash.com/photo-1731616103600-3fe7ccdc5a59?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Cargador Rápido USB-C 65W",
                            Price = 25.00m,
                            Stock = 300
                        },
                        new
                        {
                            ProductId = new Guid("bc0166e4-1ca8-40ab-a2ef-93b3d62d2638"),
                            Description = "Diseño ergonómico, compartimentos ocultos y puerto de carga USB integrado.",
                            MainImageUrl = "https://images.unsplash.com/photo-1668114844900-537ab91478b9?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Mochila Antirrobo para Portátil",
                            Price = 45.80m,
                            Stock = 110
                        });
                });

            modelBuilder.Entity("BasicEcommerce.Models.OrderItem", b =>
                {
                    b.HasOne("BasicEcommerce.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BasicEcommerce.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BasicEcommerce.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
